"""empty message

Revision ID: 2e71398c493e
Revises: b2dfbaab08c1
Create Date: 2025-11-26 23:44:58.973421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e71398c493e'
down_revision: Union[str, Sequence[str], None] = 'b2dfbaab08c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("COMMIT")
    op.execute("ALTER TYPE op_type ADD VALUE IF NOT EXISTS 'rename';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
