"""Op_type create folder

Revision ID: 8305b43af90b
Revises: e2b30845b965
Create Date: 2025-11-29 16:45:47.667359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8305b43af90b'
down_revision: Union[str, Sequence[str], None] = 'e2b30845b965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TYPE op_type ADD VALUE IF NOT EXISTS 'FOLDER_CREATE';"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
