"""Added folder propertioes to file

Revision ID: 881a8798e092
Revises: 09d987fd56ae
Create Date: 2025-11-26 16:37:56.078466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '881a8798e092'
down_revision: Union[str, Sequence[str], None] = '09d987fd56ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('parent_folder_id', sa.UUID(), nullable=True))
    op.add_column('files', sa.Column('is_folder', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'files', 'files', ['parent_folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.alter_column('files', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('files', 'is_folder')
    op.drop_column('files', 'parent_folder_id')
    # ### end Alembic commands ###
