"""dodano extension jako pole file

Revision ID: 99f6bbfac818
Revises: 8305b43af90b
Create Date: 2025-12-04 17:27:04.959430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f6bbfac818'
down_revision: Union[str, Sequence[str], None] = '8305b43af90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extension', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'extension')
    # ### end Alembic commands ###
