"""empty message

Revision ID: b2dfbaab08c1
Revises: e17ef664481a
Create Date: 2025-11-26 18:47:49.242749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dfbaab08c1'
down_revision: Union[str, Sequence[str], None] = 'e17ef664481a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_versions', sa.Column('blob_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'file_versions', 'blobs', ['blob_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_versions', type_='foreignkey')
    op.drop_column('file_versions', 'blob_id')
    # ### end Alembic commands ###
