"""Dodanie List Files i view file versions op_type

Revision ID: e2b30845b965
Revises: 45819f61285b
Create Date: 2025-11-28 16:02:01.294922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b30845b965'
down_revision: Union[str, Sequence[str], None] = '45819f61285b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blobs_sha256_key'), 'blobs', type_='unique')
    op.execute("ALTER TYPE op_type ADD VALUE IF NOT EXISTS 'LIST_FILES'")
    op.execute("ALTER TYPE op_type ADD VALUE IF NOT EXISTS 'VIEW_FILE_VERSIONS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('blobs_sha256_key'), 'blobs', ['sha256'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
